### ISSUE TITLE
Job UI - API Call Error

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#105]
the new job UI is breaking the jsonUtils jsonToMap function. We need to fix the function to handle the array.

test should also be created for this

the opening `[` in the parameters array string is breaking with the following error. 

**Breaking Section**
```
      "spark_jar_task": {
        "jar_uri": "",
        "main_class_name": "com.databricks.labs.overwatch.BatchRunner",
        "parameters": ["{\"auditLogConfig\":{\"rawAuditPath\":\"/mnt/logs/oregon2/audit_delivery\"},\"tokenSecret\":{\"scope\":\"overwatch\",\"key\":\"workspace-1029\"},\"dataTarget\":{\"databaseName\":\"overwatch_etl\",\"databaseLocation\":\"dbfs:/mnt/overwatch_global/consume/overwatch_etl.db\",\"consumerDatabaseName\":\"overwatch\",\"consumerDatabaseLocation\":\"dbfs:/mnt/overwatch_global/consume/overwatch.db\"},\"badRecordsPath\":\"/mnt/overwatch_oregon2/workspace-1029/sparkEventsBadrecords\",\"overwatchScope\":[\"all\"],\"maxDaysToLoad\":60,\"databricksContractPrices\":{\"interactiveDBUCostUSD\":0.56,\"automatedDBUCostUSD\":0.26},\"primordialDateString\":\"2021-01-16\"}"],
        "run_as_repl": true
      }
```

**Stack Trace**
```
21/04/21 12:55:47 INFO ApiCall: Loading https://westeurope-c2.azuredatabricks.net/api/2.0/jobs/list -> query: ?limit=150&offset=0
21/04/21 12:55:48 ERROR JsonUtils$: ERROR: Could not convert json to Map. 
JSON: {"jobs":[{"job_id":36,"settings":{"name":"azure_devops_demo-sample","new_cluster":{"spark_version":"7.2.x-cpu-ml-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_F4s","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":2},"libraries":[{"whl":"dbfs:/Shared/dbx/projects/azure_devops_demo/a874949cc3484570aacd06c1f975cf4f/artifacts/dist/azure_devops_demo-0.0.1-py3-none-any.whl"}],"email_notifications":{},"timeout_seconds":0,"spark_python_task":{"python_file":"dbfs:/Shared/dbx/projects/azure_devops_demo/a874949cc3484570aacd06c1f975cf4f/artifacts/azure_devops_demo/jobs/sample/entrypoint.py","parameters":["--conf-file","dbfs:/Shared/dbx/projects/azure_devops_demo/a874949cc3484570aacd06c1f975cf4f/artifacts/conf/test/sample.json"]},"max_concurrent_runs":1},"created_time":1606913736222,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":37,"settings":{"name":"azure_devops_demo-sample-integration-test","new_cluster":{"spark_version":"7.6.x-cpu-ml-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_F4s","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":1},"libraries":[{"whl":"dbfs:/Shared/dbx/projects/azure_devops_demo/c283dd7219914c93b4845e5ea8b54279/artifacts/dist/azure_devops_demo-0.0.1-py3-none-any.whl"}],"email_notifications":{},"timeout_seconds":0,"spark_python_task":{"python_file":"dbfs:/Shared/dbx/projects/azure_devops_demo/c283dd7219914c93b4845e5ea8b54279/artifacts/tests/integration/sample_test.py"},"max_concurrent_runs":1},"created_time":1606913736599,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":49,"settings":{"name":"Overwatch","new_cluster":{"cluster_name":"","spark_version":"7.6.x-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_DS3_v2","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"SPOT_WITH_FALLBACK_AZURE","spot_bid_max_price":-1.0},"num_workers":4},"libraries":[{"maven":{"coordinates":"com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.17"}},{"jar":"dbfs:/FileStore/jars/ac231a6c_10c6_4939_b903_41a76dd61e34-overwatch_assembly_0_4_1-89c38.jar"}],"email_notifications":{"on_failure":["daniel@databricks.com"],"no_alert_for_skipped_runs":false},"timeout_seconds":0,"schedule":{"quartz_cron_expression":"0 0 22 * * ?","timezone_id":"UTC","pause_status":"UNPAUSED"},"notebook_task":{"notebook_path":"/Users/alexey.ott@databricks.com/Overwatch","base_parameters":{"secretsEvHubKey":"overwatch-eventhubs","overwatchDBKey":"overwatch-pat","presentationDBName":"overwatch","secretsScope":"aott-kv","maxDaysToLoad":"60","etlDBName":"overwatch_etl","tempPath":"/tmp","primordialDateString":"2021-01-05","evhName":"overwatch-evhub"}},"max_concurrent_runs":1},"created_time":1607938882747,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":50,"settings":{"name":"test","existing_cluster_id":"1112-110804-soils854","email_notifications":{},"timeout_seconds":0,"notebook_task":{"notebook_path":"/Users/alexey.ott@databricks.com/TestJob","base_parameters":{"decimals":"50"}},"max_concurrent_runs":5},"created_time":1607940999535,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":51,"settings":{"name":"test_automated","new_cluster":{"spark_version":"6.4.x-scala2.11","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_DS3_v2","driver_node_type_id":"Standard_D8s_v3","custom_tags":{"custom":"my_custom"},"cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"autoscale":{"min_workers":1,"max_workers":4}},"libraries":[{"jar":"dbfs:/FileStore/jars/eeabcf43_d727_4911_8af3_7c1953e94a9b-spark_examples_2_11_2_4_4-575bb.jar"}],"email_notifications":{},"timeout_seconds":0,"schedule":{"quartz_cron_expression":"0 6 1 * * ?","timezone_id":"US/Eastern","pause_status":"UNPAUSED"},"notebook_task":{"notebook_path":"/Users/alexey.ott@databricks.com/TestJob","base_parameters":{"decimals":"5000"}},"max_concurrent_runs":5},"created_time":1607974185767,"creator_user_name":"daniel.tomes@databricks.com"},{"job_id":61,"settings":{"name":"Overwatch_Dev","existing_cluster_id":"1112-110804-soils854","email_notifications":{},"timeout_seconds":0,"notebook_task":{"notebook_path":"/Users/daniel.tomes@databricks.com/Overwatch_Dev","base_parameters":{"secretsEvHubKey":"overwatch-eventhubs","overwatchDBKey":"overwatch-pat","presentationDBName":"overwatch_dev","secretsScope":"aott-kv","maxDaysToLoad":"20","etlDBName":"overwatch_etl_dev","tempPath":"/tmp/overwatch_dev","primordialDateString":"2021-01-05","evhName":"overwatch-evhub"}},"max_concurrent_runs":1},"created_time":1609872815970,"creator_user_name":"daniel.tomes@databricks.com"},{"job_id":67,"settings":{"name":"TestDriverChange","new_cluster":{"spark_version":"7.4.x-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_L4s","driver_node_type_id":"Standard_L4s","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"spark_env_vars":{"PYSPARK_PYTHON":"/databricks/python3/bin/python3"},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":2},"email_notifications":{},"timeout_seconds":0,"max_concurrent_runs":1},"created_time":1610650478219,"creator_user_name":"daniel.tomes@databricks.com"},{"job_id":194,"settings":{"name":"Untitled","new_cluster":{"spark_version":"7.5.x-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_DS3_v2","spark_env_vars":{"PYSPARK_PYTHON":"/databricks/python3/bin/python3"},"enable_elastic_disk":true,"azure_attributes":{"availability":"ON_DEMAND_AZURE"},"num_workers":8},"email_notifications":{},"timeout_seconds":0,"max_concurrent_runs":1},"created_time":1614351531783,"creator_user_name":"itai.weiss@databricks.com"},{"job_id":243,"settings":{"name":"Test Context","existing_cluster_id":"1028-133057-mufti22","email_notifications":{},"timeout_seconds":0,"notebook_task":{"notebook_path":"/Users/alexey.ott@databricks.com/TestContext"},"max_concurrent_runs":1},"created_time":1615966436944,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":246,"settings":{"name":"Overwatch Spark 3","new_cluster":{"cluster_name":"","spark_version":"7.6.x-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_H8","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"SPOT_WITH_FALLBACK_AZURE","spot_bid_max_price":-1.0},"num_workers":3},"libraries":[{"jar":"dbfs:/FileStore/jars/overwatch-assembly_2.12-0.3_RC1.jar"},{"maven":{"coordinates":"com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.18"}}],"email_notifications":{"no_alert_for_skipped_runs":false},"timeout_seconds":0,"schedule":{"quartz_cron_expression":"0 15 01 ? * *","timezone_id":"UTC","pause_status":"PAUSED"},"notebook_task":{"notebook_path":"/Users/alexey.ott@databricks.com/Overwatch Spark 3","base_parameters":{"secretsEvHubKey":"overwatch-eventhubs","overwatchDBKey":"overwatch-pat","presentationDBName":"overwatch_etl_sp3","secretsScope":"aott-kv","maxDaysToLoad":"60","etlDBName":"overwatch_sp3","tempPath":"/tmp/overwatch_sp3","primordialDateString":"2021-01-05","evhName":"overwatch-evhub"}},"max_concurrent_runs":1},"created_time":1616084940548,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":281,"settings":{"name":"Test UBS","new_cluster":{"cluster_name":"","spark_version":"8.1.x-cpu-ml-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_DS3_v2","cluster_log_conf":{"dbfs":{"destination":"dbfs:/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":2},"email_notifications":{"no_alert_for_skipped_runs":false},"timeout_seconds":0,"spark_submit_task":{"parameters":["--jars","/dbfs/tmp/ubs-test/jars/*.jar","--py-files","/dbfs//tmp/ubs-test/py/code2.py","/dbfs/tmp/ubs-test/code.py","--calcID","ec4e360f-01df-4afb-a42e-1ed09419a979","--runID","R0000023350"]},"max_concurrent_runs":1},"created_time":1618324794751,"creator_user_name":"alexey.ott@databricks.com"},{"job_id":286,"settings":{"name":"Overwatch_Example","new_cluster":{"spark_version":"8.1.x-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_DS3_v2","spark_env_vars":{"PYSPARK_PYTHON":"/databricks/python3/bin/python3"},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":8},"libraries":[{"maven":{"coordinates":"com.databricks.labs:overwatch_2.12:1.0"}}],"email_notifications":{"no_alert_for_skipped_runs":false},"timeout_seconds":0,"schedule":{"quartz_cron_expression":"21 35 5 * * ?","timezone_id":"America/New_York","pause_status":"UNPAUSED"},"spark_jar_task":{"jar_uri":"","main_class_name":"com.databricks.labs.overwatch.BatchRunner","parameters":["{\"auditLogConfig\":{\"rawAuditPath\":\"/mnt/logs/oregon2/audit_delivery\"},\"tokenSecret\":{\"scope\":\"overwatch\",\"key\":\"workspace-1029\"},\"dataTarget\":{\"databaseName\":\"overwatch_etl\",\"databaseLocation\":\"dbfs:/mnt/overwatch_global/consume/overwatch_etl.db\",\"consumerDatabaseName\":\"overwatch\",\"consumerDatabaseLocation\":\"dbfs:/mnt/overwatch_global/consume/overwatch.db\"},\"badRecordsPath\":\"/mnt/overwatch_oregon2/workspace-1029/sparkEventsBadrecords\",\"overwatchScope\":[\"all\"],\"maxDaysToLoad\":60,\"databricksContractPrices\":{\"interactiveDBUCostUSD\":0.56,\"automatedDBUCostUSD\":0.26},\"primordialDateString\":\"2021-01-16\"}"],"run_as_repl":true},"max_concurrent_runs":1},"created_time":1618514519028,"creator_user_name":"daniel.tomes@databricks.com"}]}
com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries
 at [Source: (String)"{"jobs":[{"job_id":36,"settings":{"name":"azure_devops_demo-sample","new_cluster":{"spark_version":"7.2.x-cpu-ml-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_F4s","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":2},"libraries":[{"whl":"dbfs:/Shared/dbx/projects/azure_devops_demo/a8749"[truncated 9845 chars]; line: 1, column: 9612] (through reference chain: com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$BuilderWrapper["jobs"]->com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[11])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:365)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:302)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at com.databricks.labs.overwatch.utils.JsonUtils$.jsonToMap(Tools.scala:73)
	at com.databricks.labs.overwatch.ApiCall.paginate(ApiCall.scala:179)
	at com.databricks.labs.overwatch.ApiCall.executeGet(ApiCall.scala:160)
	at com.databricks.labs.overwatch.env.Workspace.getJobsDF(Workspace.scala:39)
	at com.databricks.labs.overwatch.pipeline.Bronze.appendJobsProcess$lzycompute(Bronze.scala:34)
	at com.databricks.labs.overwatch.pipeline.Bronze.appendJobsProcess(Bronze.scala:33)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1(Bronze.scala:128)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1$adapted(Bronze.scala:124)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.databricks.labs.overwatch.pipeline.Bronze.executeModules(Bronze.scala:124)
	at com.databricks.labs.overwatch.pipeline.Bronze.run(Bronze.scala:145)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-323245422188732:1)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-323245422188732:53)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-323245422188732:55)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-323245422188732:57)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-323245422188732:59)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-323245422188732:61)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw$$iw.<init>(command-323245422188732:63)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw$$iw.<init>(command-323245422188732:65)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw$$iw.<init>(command-323245422188732:67)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$$iw.<init>(command-323245422188732:69)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read.<init>(command-323245422188732:71)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$.<init>(command-323245422188732:75)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$read$.<clinit>(command-323245422188732)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$eval$.$print$lzycompute(<notebook>:7)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$eval$.$print(<notebook>:6)
	at $linee6ceaf9c4c884018a0fe2edbbc104eb737.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:235)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:830)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:783)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:235)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$11(DriverLocal.scala:488)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:240)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:235)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:232)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:50)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:277)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:270)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:50)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:465)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:690)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:682)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:523)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:635)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:428)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:371)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:223)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('a' (code 97)): was expecting comma to separate Array entries
 at [Source: (String)"{"jobs":[{"job_id":36,"settings":{"name":"azure_devops_demo-sample","new_cluster":{"spark_version":"7.2.x-cpu-ml-scala2.12","spark_conf":{"spark.databricks.delta.preview.enabled":"true"},"node_type_id":"Standard_F4s","cluster_log_conf":{"dbfs":{"destination":"dbfs:/mnt/cluster-logs"}},"enable_elastic_disk":true,"azure_attributes":{"first_on_demand":1,"availability":"ON_DEMAND_AZURE","spot_bid_max_price":-1.0},"num_workers":2},"libraries":[{"whl":"dbfs:/Shared/dbx/projects/azure_devops_demo/a8749"[truncated 9845 chars]; line: 1, column: 9616]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1840)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:712)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:637)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._skipComma(ReaderBasedJsonParser.java:2293)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:689)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapArray(UntypedObjectDeserializerModule.scala:37)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:256)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.module.scala.deser.GenericMapFactoryDeserializerResolver$Deserializer.deserialize(GenericMapFactoryDeserializerResolver.scala:71)
	at com.fasterxml.jackson.module.scala.deser.UntypedObjectDeserializer.mapObject(UntypedObjectDeserializerModule.scala:42)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer.deserialize(UntypedObjectDeserializer.java:248)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	... 75 more
21/04/21 12:55:48 INFO ApiCall: Using Databricks SparkSession
```

**Comment by GeekSheikh** [comment]
Currently, when there's a failure, the try/catch block that gets his is in the APICall.scala paginate function. There needs to be a try catch inside the API Call and likely a quarantine zone for failed records. This will allow us to fail a single record transformation instead of an entire API page call as well as allow us to find the issues.
