### ISSUE TITLE
Unresolved Column warehouse_state

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1063]
**Overwatch Version**
0.7.2.1

**Describe the bug**
On October 12th, our Overwatch job began showing an error in regards to the warehouse_state column during Gold execution. We also noticed that all job runs became substantially shorter and data is not being populated in some of the tables.

Error message (shortened)
```Gold_Warehouse: Validating Input Schemas
FAILED: 3018-Gold_Warehouse Module: Failed

[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `warehouse_state` cannot be resolved. Did you mean one of the following? [`warehouse_name`, `warehouse_type`, `warehouse_id`, `requestId`, `workspace_name`];
'Project [warehouse_id#136259, warehouse_name#136260, organization_id#136253, serviceName#136254 AS service_name#136563, actionName#136255 AS action_name#136564, userEmail#136256 AS user_email#136565, cluster_size#136261, min_num_clusters#136262L, max_num_clusters#136263L, auto_stop_mins#136264L, spot_instance_policy#136265, enable_photon#136266, channel#136267, enable_serverless_compute#136269, warehouse_type#136270, 'warehouse_state, 'size, 'auto_resume, 'creator_id, tags#136268, 'num_clusters, 'num_active_sessions, 'jdbc_url, timestamp#136251L AS unixTimeMS#136566L, ... 3 more fields]
+- Filter (organization_id#136253 = 270181971930646)
   +- Filter ((timestamp#136251L >= 1694476800000) AND (timestamp#136251L < 1697068800000))
      +- Relation [timestamp#136251L,date#136252,organization_id#136253,serviceName#136254,actionName#136255,userEmail#136256,requestId#136257,response#136258,warehouse_id#136259,warehouse_name#136260,cluster_size#136261,min_num_clusters#136262L,max_num_clusters#136263L,auto_stop_mins#136264L,spot_instance_policy#136265,enable_photon#136266,channel#136267,tags#136268,enable_serverless_compute#136269,warehouse_type#136270,Pipeline_SnapTS#136271,Overwatch_RunID#136272,workspace_name#136273] parquet
```

**Screenshots**
![image](https://github.com/databrickslabs/overwatch/assets/67801903/d6a3f19c-ca62-4f30-bf2e-0536aa2dcd53)

**Comment by mohanbaabu1996** [comment]
Hi @williamdphillips ,

Can you please send the full stack message for us to review from the pipeline_report.

`select * from ETL_DB.pipeline_report where moduleID = 3018 and status like '%FAILED%' order by Pipeline_SnapTs desc`

Please run the query by changing the ETL database name.

**Comment by williamdphillips** [comment]
@mohanbaabu1996 There are 51 rows in the dataframe from that query and they all seem to have the same error message. Let me know if you want any particular field or want me to provide more information.

**Error message:**
```
FAILED --> 
ERROR:
FAILED: 3018-Gold_Warehouse Module: Failed

[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `warehouse_state` cannot be resolved. Did you mean one of the following? [`warehouse_name`, `warehouse_type`, `warehouse_id`, `requestId`, `workspace_name`];
'Project [warehouse_id#137383, warehouse_name#137384, organization_id#137377, serviceName#137378 AS service_name#137601, actionName#137379 AS action_name#137602, userEmail#137380 AS user_email#137603, cluster_size#137385, min_num_clusters#137386L, max_num_clusters#137387L, auto_stop_mins#137388L, spot_instance_policy#137389, enable_photon#137390, channel#137391, enable_serverless_compute#137393, warehouse_type#137394, 'warehouse_state, 'size, 'auto_resume, 'creator_id, tags#137392, 'num_clusters, 'num_active_sessions, 'jdbc_url, timestamp#137375L AS unixTimeMS#137604L, ... 3 more fields]
+- Filter (organization_id#137377 = 270181971930646)
   +- Filter ((timestamp#137375L >= 1694476800000) AND (timestamp#137375L < 1697068800000))
      +- Relation [timestamp#137375L,date#137376,organization_id#137377,serviceName#137378,actionName#137379,userEmail#137380,requestId#137381,response#137382,warehouse_id#137383,warehouse_name#137384,cluster_size#137385,min_num_clusters#137386L,max_num_clusters#137387L,auto_stop_mins#137388L,spot_instance_policy#137389,enable_photon#137390,channel#137391,tags#137392,enable_serverless_compute#137393,warehouse_type#137394,Pipeline_SnapTS#137395,Overwatch_RunID#137396,workspace_name#137397] parquet

org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `warehouse_state` cannot be resolved. Did you mean one of the following? [`warehouse_name`, `warehouse_type`, `warehouse_id`, `requestId`, `workspace_name`];
'Project [warehouse_id#137383, warehouse_name#137384, organization_id#137377, serviceName#137378 AS service_name#137601, actionName#137379 AS action_name#137602, userEmail#137380 AS user_email#137603, cluster_size#137385, min_num_clusters#137386L, max_num_clusters#137387L, auto_stop_mins#137388L, spot_instance_policy#137389, enable_photon#137390, channel#137391, enable_serverless_compute#137393, warehouse_type#137394, 'warehouse_state, 'size, 'auto_resume, 'creator_id, tags#137392, 'num_clusters, 'num_active_sessions, 'jdbc_url, timestamp#137375L AS unixTimeMS#137604L, ... 3 more fields]
+- Filter (organization_id#137377 = 270181971930646)
   +- Filter ((timestamp#137375L >= 1694476800000) AND (timestamp#137375L < 1697068800000))
      +- Relation [timestamp#137375L,date#137376,organization_id#137377,serviceName#137378,actionName#137379,userEmail#137380,requestId#137381,response#137382,warehouse_id#137383,warehouse_name#137384,cluster_size#137385,min_num_clusters#137386L,max_num_clusters#137387L,auto_stop_mins#137388L,spot_instance_policy#137389,enable_photon#137390,channel#137391,tags#137392,enable_serverless_compute#137393,warehouse_type#137394,Pipeline_SnapTS#137395,Overwatch_RunID#137396,workspace_name#137397] parquet

	at org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:186)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:117)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$7(CheckAnalysis.scala:237)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$7$adapted(CheckAnalysis.scala:223)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:295)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$6(CheckAnalysis.scala:223)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$6$adapted(CheckAnalysis.scala:223)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$2(CheckAnalysis.scala:223)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$2$adapted(CheckAnalysis.scala:125)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:295)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:125)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:120)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:120)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:252)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:306)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:361)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:303)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:147)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:340)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$3(QueryExecution.scala:337)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:763)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:337)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:334)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:141)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:141)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:133)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.Dataset.withPlan(Dataset.scala:4332)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1631)
	at com.databricks.labs.overwatch.pipeline.GoldTransforms.buildWarehouse(GoldTransforms.scala:930)
	at com.databricks.labs.overwatch.pipeline.GoldTransforms.buildWarehouse$(GoldTransforms.scala:898)
	at com.databricks.labs.overwatch.pipeline.Gold.buildWarehouse(Gold.scala:8)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$appendWarehouseProcess$2(Gold.scala:304)
	at org.apache.spark.sql.Dataset.transform(Dataset.scala:3170)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.$anonfun$executeETL$1(ETLDefinition.scala:30)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.executeETL(ETLDefinition.scala:28)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:388)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1(Gold.scala:378)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1$adapted(Gold.scala:350)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:350)
	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:453)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:256)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:456)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by dougspadotto** [comment]
I've also observed the same issue while using Overwatch 0.7.2.2.

Full stack trace here:

workspace_name,moduleName,status
WorkSpace_BigData,Gold_Warehouse,"FAILED --> 
ERROR:
FAILED: 3018-Gold_Warehouse Module: Failed

[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `warehouse_state` cannot be resolved. Did you mean one of the following? [`warehouse_name`, `warehouse_type`, `warehouse_id`, `requestId`, `workspace_name`];
'Project [warehouse_id#8147147, warehouse_name#8147148, organization_id#8147141, serviceName#8147142 AS service_name#8148879, actionName#8147143 AS action_name#8148880, userEmail#8147144 AS user_email#8148881, cluster_size#8147149, min_num_clusters#8147150L, max_num_clusters#8147151L, auto_stop_mins#8147152L, spot_instance_policy#8147153, enable_photon#8147154, channel#8147155, enable_serverless_compute#8147157, warehouse_type#8147158, 'warehouse_state, 'size, 'auto_resume, 'creator_id, tags#8147156, 'num_clusters, 'num_active_sessions, 'jdbc_url, timestamp#8147139L AS unixTimeMS#8148882L, ... 3 more fields]
+- Filter (organization_id#8147141 = 274532555602504)
   +- Filter ((timestamp#8147139L >= 1691020800000) AND (timestamp#8147139L < 1693612800000))
      +- Relation [timestamp#8147139L,date#8147140,organization_id#8147141,serviceName#8147142,actionName#8147143,userEmail#8147144,requestId#8147145,response#8147146,warehouse_id#8147147,warehouse_name#8147148,cluster_size#8147149,min_num_clusters#8147150L,max_num_clusters#8147151L,auto_stop_mins#8147152L,spot_instance_policy#8147153,enable_photon#8147154,channel#8147155,tags#8147156,enable_serverless_compute#8147157,warehouse_type#8147158,Pipeline_SnapTS#8147159,Overwatch_RunID#8147160,workspace_name#8147161] parquet

org.apache.spark.sql.AnalysisException: [UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `warehouse_state` cannot be resolved. Did you mean one of the following? [`warehouse_name`, `warehouse_type`, `warehouse_id`, `requestId`, `workspace_name`];
'Project [warehouse_id#8147147, warehouse_name#8147148, organization_id#8147141, serviceName#8147142 AS service_name#8148879, actionName#8147143 AS action_name#8148880, userEmail#8147144 AS user_email#8148881, cluster_size#8147149, min_num_clusters#8147150L, max_num_clusters#8147151L, auto_stop_mins#8147152L, spot_instance_policy#8147153, enable_photon#8147154, channel#8147155, enable_serverless_compute#8147157, warehouse_type#8147158, 'warehouse_state, 'size, 'auto_resume, 'creator_id, tags#8147156, 'num_clusters, 'num_active_sessions, 'jdbc_url, timestamp#8147139L AS unixTimeMS#8148882L, ... 3 more fields]
+- Filter (organization_id#8147141 = 274532555602504)
   +- Filter ((timestamp#8147139L >= 1691020800000) AND (timestamp#8147139L < 1693612800000))
      +- Relation [timestamp#8147139L,date#8147140,organization_id#8147141,serviceName#8147142,actionName#8147143,userEmail#8147144,requestId#8147145,response#8147146,warehouse_id#8147147,warehouse_name#8147148,cluster_size#8147149,min_num_clusters#8147150L,max_num_clusters#8147151L,auto_stop_mins#8147152L,spot_instance_policy#8147153,enable_photon#8147154,channel#8147155,tags#8147156,enable_serverless_compute#8147157,warehouse_type#8147158,Pipeline_SnapTS#8147159,Overwatch_RunID#8147160,workspace_name#8147161] parquet

	at org.apache.spark.sql.errors.QueryCompilationErrors$.unresolvedAttributeError(QueryCompilationErrors.scala:186)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.org$apache$spark$sql$catalyst$analysis$CheckAnalysis$$failUnresolvedAttribute(CheckAnalysis.scala:117)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$7(CheckAnalysis.scala:237)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$7$adapted(CheckAnalysis.scala:223)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:295)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$6(CheckAnalysis.scala:223)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$6$adapted(CheckAnalysis.scala:223)
	at scala.collection.immutable.Stream.foreach(Stream.scala:533)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$2(CheckAnalysis.scala:223)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$2$adapted(CheckAnalysis.scala:125)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:295)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:125)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:120)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:120)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:252)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:306)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:361)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:303)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:147)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:340)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$3(QueryExecution.scala:337)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:763)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:337)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:334)
	at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:141)
	at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:141)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:133)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:99)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.Dataset.withPlan(Dataset.scala:4332)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1631)
	at com.databricks.labs.overwatch.pipeline.GoldTransforms.buildWarehouse(GoldTransforms.scala:930)
	at com.databricks.labs.overwatch.pipeline.GoldTransforms.buildWarehouse$(GoldTransforms.scala:898)
	at com.databricks.labs.overwatch.pipeline.Gold.buildWarehouse(Gold.scala:8)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$appendWarehouseProcess$2(Gold.scala:304)
	at org.apache.spark.sql.Dataset.transform(Dataset.scala:3170)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.$anonfun$executeETL$1(ETLDefinition.scala:30)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.executeETL(ETLDefinition.scala:28)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:388)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1(Gold.scala:378)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1$adapted(Gold.scala:350)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:350)
	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:453)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:256)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:456)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by williamdphillips** [comment]
Hi @gueniai, we are seeing data flowing through the EH which we also capture in LogAnalytics. Queries show data from the dates which overwatch is currently skipping. For "Warehouse Spec" I'm not sure where we would see that, but we have all metrics being captured so we should be seeing it.

Yes, we can grant access for the workspace where Overwatch is running for further investigation. I will follow up with an email granting consent.

**Comment by mohanbaabu1996** [comment]
Hi @williamdphillips and @dougspadotto ,

Can you please run the repair [script](https://databrickslabs.github.io/overwatch/changelog/#07221-patch) attached in the latest version to fix the DBSQL module? Make sure to add the latest library (07221) in the cluster while running the script and update the library to the overwatch as well. Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @williamdphillips,

Let me know if it works?

**Comment by williamdphillips** [comment]
Hi @mohanbaabu1996, I've run the script to fix the module and updated to latest library. However, before confirming whether it is fixed we are working on another issue to authenticate to eventhub with AAD. Once we fix the other issue I will check and respond back. Thanks.

**Comment by mohanbaabu1996** [comment]
Thanks @williamdphillips, please re-open the ticket, if you have any issues.

**Comment by williamdphillips** [comment]
Hi @mohanbaabu1996, today we re-executed overwatch after we had run the script for fixing it a week back. One of the commands in the notebook provided as a fix may have failed:

![image](https://github.com/databrickslabs/overwatch/assets/67801903/0d89807b-b731-478b-a3e0-ed20557b131e)

We are still seeing the same error in pipeline as well:

[UNRESOLVED_COLUMN.WITH_SUGGESTION] A column or function parameter with name `warehouse_state` cannot be resolved. Did you mean one of the following? [`warehouse_name`, `warehouse_type`, `warehouse_id`, `requestId`, `workspace_name`];
'Project [timestamp#92608L, date#92609, organization_id#92610, serviceName#92611, actionName#92612, userEmail#92613, requestId#92614, response#92615, warehouse_id#92616, warehouse_name#92617, cluster_size#92618, min_num_clusters#92619L, max_num_clusters#92620L, auto_stop_mins#92621L, spot_instance_policy#92622, enable_photon#92623, channel#92624, tags#92625, enable_serverless_compute#92626, warehouse_type#92627, 'warehouse_state, 'size, 'auto_resume, 'creator_id, ... 5 more fields]
+- Filter (organization_id#92610 = 270181971930646)
   +- Relation [timestamp#92608L,date#92609,organization_id#92610,serviceName#92611,actionName#92612,userEmail#92613,requestId#92614,response#92615,warehouse_id#92616,warehouse_name#92617,cluster_size#92618,min_num_clusters#92619L,max_num_clusters#92620L,auto_stop_mins#92621L,spot_instance_policy#92622,enable_photon#92623,channel#92624,tags#92625,enable_serverless_compute#92626,warehouse_type#92627,Pipeline_SnapTS#92628,Overwatch_RunID#92629,workspace_name#92630] parquet

**Comment by mohanbaabu1996** [comment]
Hi @williamdphillips ,

Can you re-run the upgrade [script](https://databrickslabs.github.io/overwatch/assets/ChangeLog/07221_upgrade.html) by removing the gold layer `3018` . Once the upgrade script completed, then re-run the job pipeline with the latest version 07221.

<img width="1672" alt="image" src="https://github.com/databrickslabs/overwatch/assets/87074323/ffe2396d-f538-42e4-8c26-b46a341b7964">

**Comment by dougspadotto** [comment]
Hi @mohanbaabu1996 , I still get the None.get error even after setting only the silver stage for rollback.

<img width="1508" alt="image" src="https://github.com/databrickslabs/overwatch/assets/5835211/8889524b-ad50-4f06-9eb6-e96f18218387">

Could it be that some of the workspaces never had that module ever run?

**Comment by mohanbaabu1996** [comment]
Yes, Exactly.

In the above parameter, you can pass the workspace ID for which it has the silver warehouse module
