### ISSUE TITLE
NullPointerException when using msal4j

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1073]
**Overwatch Version**
0.7.2.1

**Describe the bug**
Prior to using Entra ID (AAD) authentication for EventHubs we were using SAS-based authentication with no issues. However, due to new policies at our company, we are no longer able to use SAS-based authentication. Initially, we ran into an issue with library installation which was resolved by changing the order of libraries in the task (Image 1). 

After that issue was resolved, we are now getting a NullPointerException when running Overwatch that we are unable to resolve.

**Screenshots**
When msal4j is installed last, the job fails due to the error: "com.sun.mail:javax.mail download failed". 
![image](https://github.com/databrickslabs/overwatch/assets/67801903/e8c92d04-2a72-404f-a444-21f87fdac096)

This issue is resolved by changing order of library installation.
![image](https://github.com/databrickslabs/overwatch/assets/67801903/c8fbc45f-2f7d-442a-bc98-286e5677c787)

**Error Stacktrace**
```
Got Exception while building params
null
java.lang.NullPointerException
	at java.util.Calendar.setTime(Calendar.java:1770)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:943)
	at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
	at java.text.DateFormat.format(DateFormat.java:345)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.buildParams(MultiWorkspaceDeployment.scala:152)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$deploy$1(MultiWorkspaceDeployment.scala:485)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.deploy(MultiWorkspaceDeployment.scala:485)
	at com.databricks.labs.overwatch.MultiWorkspaceRunner$.main(MultiWorkspaceRunner.scala:46)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command--1:1)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$$iw$$iw$$iw$$iw$$iw.<init>(command--1:43)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$$iw$$iw$$iw$$iw.<init>(command--1:45)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$$iw$$iw$$iw.<init>(command--1:47)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$$iw$$iw.<init>(command--1:49)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$$iw.<init>(command--1:51)
	at $linef584702c1a204b61a2a467488654c4ac25.$read.<init>(command--1:53)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$.<init>(command--1:57)
	at $linef584702c1a204b61a2a467488654c4ac25.$read$.<clinit>(command--1)
	at $linef584702c1a204b61a2a467488654c4ac25.$eval$.$print$lzycompute(<notebook>:7)
	at $linef584702c1a204b61a2a467488654c4ac25.$eval$.$print(<notebook>:6)
	at $linef584702c1a204b61a2a467488654c4ac25.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:223)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:225)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1129)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:1082)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$24(DriverLocal.scala:740)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:124)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$21(DriverLocal.scala:723)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:403)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:147)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:401)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:398)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:446)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:431)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:62)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:700)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:622)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:614)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:533)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:568)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:438)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:381)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:232)
	at java.lang.Thread.run(Thread.java:750)

```

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by williamdphillips** [comment]
Actually it appears this may be caused by loading CSV in excel and the formatting of the date being changed. Will verify if that is the case and close the issue if we are able to resolve.

**Comment by williamdphillips** [comment]
Issue with date format was causing error shown in stacktrace. Closing the issue.
