### ISSUE TITLE
Overwatch stopped collecting SQL query history

### ISSUE THREAD

**Issue by smatsui** [databrickslabs/overwatch#1075]
**Sensitive Content Alert**
Please remember that this repository is publicly visible so do not post anything sensitive in your report such as user emails, secrets, etc.

**Overwatch Version**
Tell us the version of Overwatch used when you received the issue

com.databricks.labs:overwatch_2.12:0.7.2.0.1

**Describe the bug**

SQL query history has not been collected for about 10 days.

We are deploying Overwatch everyday to collect Databricks logs and metrics.
Databricks query history page shows a lot of queries for the past 10 days, but Overwatch stopped collecting logs for `overwatch.sqlqueryhistory` table. When I run `SELECT * FROM overwatch.sqlqueryhistory ORDER BY query_end_time_ms DESC`, the newest query is from 10 days ago.

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

The report shows no new data found for SQL query history:

```csv
3029...0602,3017,Gold_Sql_QueryHistory,2023-05-22,2023-10-26T06:08:37.284+0000,2023-10-27T06:08:14.667+0000,"EMPTY: 3017-Gold_Sql_QueryHistory Module: No new data found. This does not appear to be an error but simply a lack of data present for the module. Progressing module state.
 Module Dependencies: 2020
ALERT: No New Data Retrieved for Module 3017-Gold_Sql_QueryHistory! Skipping
com.databricks.labs.overwatch.utils.NoNewDataException: ALERT: No New Data Retrieved for Module 3017-Gold_Sql_QueryHistory! Skipping
        at com.databricks.labs.overwatch.pipeline.Module.validateSourceDF(Module.scala:317)
        at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:376)
        at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1(Gold.scala:342)
        at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1$adapted(Gold.scala:315)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:315)
        at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:408)
        at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:256)
        at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:454)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
",{},2023-10-27T06:36:41.000+0000,f73e12a13ae244aa95613c1856dc803f
3029...0602,2020,Silver_SQLQueryHistory,2023-05-22,2023-10-26T06:08:37.284+0000,2023-10-27T06:08:14.667+0000,"EMPTY: 2020-Silver_SQLQueryHistory Module: No new data found. This does not appear to be an error but simply a lack of data present for the module. Progressing module state.
 Module Dependencies: 1004
ALERT: No New Data Retrieved for Module 2020-Silver_SQLQueryHistory! Skipping
com.databricks.labs.overwatch.utils.NoNewDataException: ALERT: No New Data Retrieved for Module 2020-Silver_SQLQueryHistory! Skipping
        at com.databricks.labs.overwatch.pipeline.Module.validateSourceDF(Module.scala:317)
        at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:376)
        at com.databricks.labs.overwatch.pipeline.Silver.$anonfun$executeModules$1(Silver.scala:392)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at com.databricks.labs.overwatch.pipeline.Silver.executeModules(Silver.scala:382)
        at com.databricks.labs.overwatch.pipeline.Silver.run(Silver.scala:408)
        at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startSilverDeployment(MultiWorkspaceDeployment.scala:231)
        at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:453)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
        at scala.util.Success.$anonfun$map$1(Try.scala:255)
        at scala.util.Success.map(Try.scala:213)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
",{},2023-10-27T06:18:09.000+0000,f73e12a13ae244aa95613c1856dc803f
```

**Comment by Neha-vs123** [comment]
Hi @smatsui,

Please upgrade to the latest version, 0.7.2.2 by following the [docs](https://databrickslabs.github.io/overwatch/changelog/#0722)  and run the pipeline. Please let me know if the issue is persisting.

Regards,
Neha

**Comment by smatsui** [comment]
Hi @Neha-vs123,

I upgrade to 0.7.2.2 and deployed Overwatch again, but the issue still persists.

**Comment by sriram251-code** [comment]
Hi @smatsui can u create a SF ticket for the same so that i can login to the environment and check the issue.

**Comment by smatsui** [comment]
Hi @sriram251-code, I opened #00390000.

**Comment by sriram251-code** [comment]
please update the workspaceID in the ticket, and provide the notebook which you are using for the reference in the ticket.

**Comment by smatsui** [comment]
I added the workspace ID and the URL to the ticket.

**Comment by sriram251-code** [comment]
Hi @smatsui after doing the manual analysis we have the below are the findings .
The sqlqueryhistory module calls sql/history/queries api to get the data.After making the call manually we found no response.
Please find the screen shot attached. In the SF ticket.
