### ISSUE TITLE
Clean Installation Azure Eventhub Chekpoint Directory Issue

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1099]
**Overwatch Version**
0.7.2.2.1

**Describe the bug**
During clean installation of Overwatch the deployment report indicated an error for the eventhub checkpoint. The directory was empty when the job began running.

**Expected Behavior**
Overwatch should not throw an error indicating that the directory was nonempty when it was empty when job began running.

**Error**
```Got Exception while Deploying,
ERROR: Azure Event Hub checkpoint directory issue.
PATH: dbfs:/mnt/overwatch/dev_test/270181971930646/ehState/rawEventsCheckpoint is not empty. First run requires empty checkpoints. exists:true, isFirstRun:true
com.databricks.labs.overwatch.utils.BadConfigException: ERROR: Azure Event Hub checkpoint directory issue.
PATH: dbfs:/mnt/overwatch/dev_test/270181971930646/ehState/rawEventsCheckpoint is not empty. First run requires empty checkpoints. exists:true, isFirstRun:true
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.$anonfun$validateCleanPaths$2(BronzeTransforms.scala:183)
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.$anonfun$validateCleanPaths$2$adapted(BronzeTransforms.scala:166)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.validateCleanPaths(BronzeTransforms.scala:166)
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.landAzureAuditLogDF(BronzeTransforms.scala:229)
	at com.databricks.labs.overwatch.pipeline.BronzeTransforms.landAzureAuditLogDF$(BronzeTransforms.scala:205)
	at com.databricks.labs.overwatch.pipeline.Bronze.landAzureAuditLogDF(Bronze.scala:8)
	at com.databricks.labs.overwatch.pipeline.Bronze.landAzureAuditEvents(Bronze.scala:295)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1(Bronze.scala:309)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Bronze.executeModules(Bronze.scala:306)
	at com.databricks.labs.overwatch.pipeline.Bronze.run(Bronze.scala:348)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startBronzeDeployment(MultiWorkspaceDeployment.scala:206)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:454)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)```

**Comment by Mahalakshmi1305** [comment]
Hi @williamdphillips 

If this is a fresh deployment, kindly remove the checkpoint directory.

**Comment by williamdphillips** [comment]
Hi @Mahalakshmi1305, the checkpoint directory was removed. There were no files in the directory when the job started. During job execution files were added and error was thrown.

**Comment by mohanbaabu1996** [comment]
Related to #1098

**Comment by williamdphillips** [comment]
This was caused by incorrect configuration values setup in our overwatch config csv file. Multiple rows had the same value for workspace id, rather than having the correct workspace id for each respective row.

After updating the config, the error no longer occurred. Closing this issue as resolved.
