### ISSUE TITLE
Multiple active records found in overwatch_etl.instanceDetails

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1100]
**Overwatch Version**
0.7.2.2.1

**Describe the bug**
During clean deployment of Overwatch the gold zone failed with error indicating that the instanceDetails table had multiple records active for a sku.

**Screenshots**
Checked whether there were duplicate records in the table and none seem to be present.
![image](https://github.com/databrickslabs/overwatch/assets/67801903/444013e5-63a5-47c4-ac85-6dcd1fef2aa1)
![image](https://github.com/databrickslabs/overwatch/assets/67801903/fee2f821-bc66-41ea-bcad-9319d299efe1)

**Error**
```Got Exception while Deploying,
Multiple active records found in overwatch_etl.instanceDetails. Only one record may be active for each sku at a time. Please review this table and correct it.
com.databricks.labs.overwatch.utils.BadConfigException: Multiple active records found in overwatch_etl.instanceDetails. Only one record may be active for each sku at a time. Please review this table and correct it.
	at com.databricks.labs.overwatch.pipeline.PipelineFunctions$.validateType2Input(PipelineFunctions.scala:445)
	at com.databricks.labs.overwatch.pipeline.Gold.validateCostSources(Gold.scala:345)
	at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:349)
	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:453)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:256)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:456)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)```

**Comment by williamdphillips** [comment]
Hi @mohanbaabu1996, This issue is still prevalent and causing issues in our Overwatch job. The job seems to detect the isntanceDetails table having multiple values even though this is created by the job itself (one record per workspace):

Image 1:
![image](https://github.com/databrickslabs/overwatch/assets/67801903/94398aa0-d225-413e-bb4d-aa2536f7a0a7)

Image 2:
![image](https://github.com/databrickslabs/overwatch/assets/67801903/831236c1-30d9-46b8-91ab-6ac17b486870)

**Comment by mohanbaabu1996** [comment]
Hi @williamdphillips ,

I hope this is due to this [issue](https://github.com/databrickslabs/overwatch/issues/1101). Please feel free to reopen the ticket, if you still facing the issue.
Thanks!
