### ISSUE TITLE
Eventhub Partition Key Not Found

### ISSUE THREAD

**Issue by williamdphillips** [databrickslabs/overwatch#1101]
**Overwatch Version**
0.7.2.2.1

**Describe the bug**
During second run of clean overwatch installation, the following error occurred. This error also happened on previous installations as well, being the main reason we decided to start fresh and remove all data/tables/schemas/etc.

**Error**
```Got Exception while Deploying,
Query StreamTo_audit_log_raw_events_270181971930646 [id = a9d04548-1b47-4ae3-aeca-b256d4db7888, runId = 7c2ee9bb-03ae-4f4e-ae79-c1265afceec5] terminated with exception: key not found: {"ehName":"azuse2cortexdataengnpddbx1-eventhub","partitionId":16}
org.apache.spark.sql.streaming.StreamingQueryException: key not found: {"ehName":"azuse2cortexdataengnpddbx1-eventhub","partitionId":16}
=== Streaming Query ===
Identifier: StreamTo_audit_log_raw_events_270181971930646 [id = a9d04548-1b47-4ae3-aeca-b256d4db7888, runId = 7c2ee9bb-03ae-4f4e-ae79-c1265afceec5]
Current Committed Offsets: {org.apache.spark.sql.eventhubs.EventHubsSource@9fc40da: {"azuse2cortexdataengnpddbx1-eventhub":{"23":2625,"8":2624,"17":2620,"26":2626,"11":2623,"29":2623,"2":2617,"20":2623,"5":2621,"14":2620,"4":2618,"13":2621,"31":2620,"22":2622,"7":2624,"16":2619,"25":2624,"10":2625,"1":2618,"28":2624,"19":2623,"27":2626,"9":2623,"18":2620,"12":2621,"3":2616,"21":2627,"30":2619,"15":2622,"6":2623,"24":2623,"0":2620}}}
Current Available Offsets: {org.apache.spark.sql.eventhubs.EventHubsSource@9fc40da: {"azuse2cortexdataengnpddbx1-eventhub":{"23":2625,"8":2624,"17":2620,"26":2626,"11":2623,"29":2623,"2":2617,"20":2623,"5":2621,"14":2620,"4":2618,"13":2621,"31":2621,"22":2622,"7":2624,"16":2619,"25":2624,"10":2625,"1":2618,"28":2624,"19":2623,"27":2628,"9":2623,"18":2620,"12":2621,"3":2616,"21":2627,"30":2620,"15":2622,"6":2623,"24":2623,"0":2620}}}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
WriteToMicroBatchDataSourceV1 DeltaSink[dbfs:/mnt/overwatch/dev_test/global_share/audit_log_raw_events], a9d04548-1b47-4ae3-aeca-b256d4db7888, [queryName=StreamTo_audit_log_raw_events_270181971930646, path=dbfs:/mnt/overwatch/dev_test/global_share/audit_log_raw_events, checkpointLocation=dbfs:/mnt/overwatch/dev_test/270181971930646/ehState/rawEventsCheckpoint, mergeSchema=true, userMetadata=*********(redacted)], Append
+- Project [body#3677, partition#3678, offset#3680, sequenceNumber#3682L, enqueuedTime#3684, publisher#3687, partitionKey#3688, properties#3690, systemProperties#3693, deserializedBody#3732, organization_id#3766, Overwatch_RunID#3802, Pipeline_SnapTS#3840, AZUSE2CORTEXDATASPECNPDDBX1 AS workspace_name#3883]
   +- Project [body#3677, partition#3678, offset#3680, sequenceNumber#3682L, enqueuedTime#3684, publisher#3687, partitionKey#3688, properties#3690, systemProperties#3693, deserializedBody#3732, organization_id#3766, Overwatch_RunID#3802, cast(from_unixtime(cast((cast(1701188141318 as double) / cast(1000 as double)) as bigint), yyyy-MM-dd HH:mm:ss, Some(Etc/UTC)) as timestamp) AS Pipeline_SnapTS#3840]
      +- Project [body#3677, partition#3678, offset#3680, sequenceNumber#3682L, enqueuedTime#3684, publisher#3687, partitionKey#3688, properties#3690, systemProperties#3693, deserializedBody#3732, organization_id#3766, babe00da30ad4af0b0e02a7e2d78cfa4 AS Overwatch_RunID#3802]
         +- Project [body#3677, partition#3678, offset#3680, sequenceNumber#3682L, enqueuedTime#3684, publisher#3687, partitionKey#3688, properties#3690, systemProperties#3693, deserializedBody#3732, 270181971930646 AS organization_id#3766]
            +- Project [body#3677, partition#3678, offset#3680, sequenceNumber#3682L, enqueuedTime#3684, publisher#3687, partitionKey#3688, properties#3690, systemProperties#3693, cast(body#3677 as string) AS deserializedBody#3732]
               +- StreamingExecutionRelation org.apache.spark.sql.eventhubs.EventHubsSource@9fc40da, [body#3677, partition#3678, offset#3680, sequenceNumber#3682L, enqueuedTime#3684, publisher#3687, partitionKey#3688, properties#3690, systemProperties#3693]

	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:397)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:404)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:147)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:402)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:399)
	at com.databricks.spark.util.PublicDBLogging.withAttributionContext(DatabricksSparkUsageLogger.scala:24)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:447)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:432)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags(DatabricksSparkUsageLogger.scala:24)
	at com.databricks.spark.util.PublicDBLogging.withAttributionTags0(DatabricksSparkUsageLogger.scala:68)
	at com.databricks.spark.util.DatabricksSparkUsageLogger.withAttributionTags(DatabricksSparkUsageLogger.scala:168)
	at com.databricks.spark.util.UsageLogging.$anonfun$withAttributionTags$1(UsageLogger.scala:495)
	at com.databricks.spark.util.UsageLogging$.withAttributionTags(UsageLogger.scala:607)
	at com.databricks.spark.util.UsageLogging$.withAttributionTags(UsageLogger.scala:616)
	at com.databricks.spark.util.UsageLogging.withAttributionTags(UsageLogger.scala:495)
	at com.databricks.spark.util.UsageLogging.withAttributionTags$(UsageLogger.scala:493)
	at org.apache.spark.sql.execution.streaming.StreamExecution.withAttributionTags(StreamExecution.scala:81)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:321)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.$anonfun$run$2(StreamExecution.scala:261)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:125)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:261)
Caused by: java.util.NoSuchElementException: key not found: {"ehName":"azuse2cortexdataengnpddbx1-eventhub","partitionId":16}
	at scala.collection.MapLike.default(MapLike.scala:236)
	at scala.collection.MapLike.default$(MapLike.scala:235)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:65)
	at org.apache.spark.sql.eventhubs.EventHubsSource.$anonfun$adjustStartingOffset$1(EventHubsSource.scala:250)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:400)
	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:728)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.eventhubs.EventHubsSource.adjustStartingOffset(EventHubsSource.scala:248)
	at org.apache.spark.sql.eventhubs.EventHubsSource.getBatch(EventHubsSource.scala:367)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$populateStartOffsets$3(MicroBatchExecution.scala:533)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:27)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.populateStartOffsets(MicroBatchExecution.scala:530)
	at org.apache.spark.sql.execution.streaming.MultiBatchRollbackSupport.populateStartOffsetsWithRollbackHandling(MultiBatchRollbackSupport.scala:112)
	at org.apache.spark.sql.execution.streaming.MultiBatchRollbackSupport.populateStartOffsetsWithRollbackHandling$(MultiBatchRollbackSupport.scala:79)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.populateStartOffsetsWithRollbackHandling(MicroBatchExecution.scala:57)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStreamWithListener$2(MicroBatchExecution.scala:380)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:336)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:334)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:81)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStreamWithListener$1(MicroBatchExecution.scala:370)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:67)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStreamWithListener(MicroBatchExecution.scala:360)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:307)
	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$2(StreamExecution.scala:374)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:338)
	... 23 more
```

**Comment by Mahalakshmi1305** [comment]
Hi, @williamdphillips

1. Have you checked the validation report to see if the eventhub succeeded or not?
2. What is the DBR version you are using to run the job?

Regards,
Mahalakshmi

**Comment by williamdphillips** [comment]
Hi @Mahalakshmi1305, by validation report which one are you referring to?

Here is the deployment report from last run (let me know if you want to see more detail):
![image](https://github.com/databrickslabs/overwatch/assets/67801903/fca9ba0b-e160-42cb-91f7-6620e158dae4)


Here is the event hub status showing messages are flowing:
![image](https://github.com/databrickslabs/overwatch/assets/67801903/935348cb-bc9d-49f7-9ee4-4761ca3bb71b)

**Comment by Mahalakshmi1305** [comment]
Can you please run the following command by changing etl_storage_prefix to yours and share the report with me?

select * from delta.`<etl_storage_prefix>/report/validationReport` where validated = 'false'
order by snapTS desc

**Comment by williamdphillips** [comment]
There is no validation report being generated and therefore query fails

![image](https://github.com/databrickslabs/overwatch/assets/67801903/9b5deeb0-fc91-41c6-b3eb-14d15ed2f41e)

**Comment by williamdphillips** [comment]
This was caused by incorrect configuration values setup in our overwatch config csv file. Multiple rows had the same value for workspace id, rather than having the correct workspace id for each respective row.

After updating the config, the error no longer occurred. Closing this issue as resolved.
