### ISSUE TITLE
PERMISSION_DENIED: This API is reserved to admin users

### ISSUE THREAD

**Issue by hazearias** [databrickslabs/overwatch#1113]
**Overwatch Version**
com.databricks.labs:overwatch_2.12:0.7.2.2.1

**Describe the bug**

	at com.databricks.labs.overwatch.api.ApiCallV2.execute(ApiCallV2.scala:669)
	at com.databricks.labs.overwatch.env.Workspace.getGlobalInitScripts(Workspace.scala:253)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$appendGlobalInitScProcess$1(Bronze.scala:259)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:386)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1(Bronze.scala:330)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Bronze.executeModules(Bronze.scala:306)
	at com.databricks.labs.overwatch.pipeline.Bronze.run(Bronze.scala:348)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startBronzeDeployment(MultiWorkspaceDeployment.scala:206)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:454)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.databricks.labs.overwatch.utils.ApiCallFailure: {"error_code":"PERMISSION_DENIED","message":"This API is reserved to admin users."}
	at com.databricks.labs.overwatch.api.ApiCallV2.responseCodeHandler(ApiCallV2.scala:344)
	at com.databricks.labs.overwatch.api.ApiCallV2.executeHelper$1(ApiCallV2.scala:639)
	at com.databricks.labs.overwatch.api.ApiCallV2.execute(ApiCallV2.scala:656)
	... 19 more

**Screenshots**
If applicable, add screenshots to help explain your problem. Be sure to blur or cover any sensitive data.

**Issue Reports**
Please provide the reports requested from the [Troubleshooting](https://placeholder) page in the docs.

**Comment by dipayan-dutta** [comment]
That PAT doesn’t have an admin access, that’s why this issue.

**Comment by hazearias** [comment]
Thanks, that works
