### ISSUE TITLE
Gold_jobRunCostPotentialFact is failing both in first run and incremental run on overwatch package- com.databricks.labs:overwatch_2.12:0.8.0.1

### ISSUE THREAD

**Issue by Saurabh910** [databrickslabs/overwatch#1179]
Gold_jobRunCostPotentialFact: Validating Input Schemas
FAILED: 3015-Gold_jobRunCostPotentialFact Module: Failed

Unsupported component type interface scala.collection.Seq in arrays.
org.apache.spark.sql.AnalysisException: Unsupported component type interface scala.collection.Seq in arrays.
	at org.apache.spark.sql.errors.QueryCompilationErrors$.arrayComponentTypeUnsupportedError(QueryCompilationErrors.scala:1552)
	at org.apache.spark.sql.catalyst.expressions.Literal$.componentTypeToDataType(literals.scala:153)
	at org.apache.spark.sql.catalyst.expressions.Literal$.apply(literals.scala:97)
	at org.apache.spark.sql.Dataset.$anonfun$hint$1(Dataset.scala:1530)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.Dataset.hint(Dataset.scala:1491)
	at com.databricks.labs.overwatch.pipeline.WorkflowsTransforms$.jrcpDeriveRunIntermediateStates(WorkflowsTransforms.scala:1293)
	at com.databricks.labs.overwatch.pipeline.WorkflowsTransforms$.jrcpDeriveRunsByClusterState(WorkflowsTransforms.scala:1375)
	at com.databricks.labs.overwatch.pipeline.GoldTransforms.buildJobRunCostPotentialFact(GoldTransforms.scala:462)
	at com.databricks.labs.overwatch.pipeline.GoldTransforms.buildJobRunCostPotentialFact$(GoldTransforms.scala:409)
	at com.databricks.labs.overwatch.pipeline.Gold.buildJobRunCostPotentialFact(Gold.scala:8)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$appendJobRunCostPotentialFactProcess$2(Gold.scala:167)
	at org.apache.spark.sql.Dataset.transform(Dataset.scala:3495)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.$anonfun$executeETL$1(ETLDefinition.scala:30)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.executeETL(ETLDefinition.scala:28)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:390)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$buildFacts$1(Gold.scala:396)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$buildFacts$1$adapted(Gold.scala:390)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Gold.buildFacts(Gold.scala:390)
	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:454)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:292)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:491)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by Mahalakshmi1305** [comment]
Hi @Saurabh910 

1. Is this a fresh deployment?
2. Which cloud are you in?
3. What is the current DBR version?

Regards,
Mahalakshmi

**Comment by Saurabh910** [comment]
Hi @Mahalakshmi1305 ,

Yes, this is a fresh deployment in AWS and I am using 14.3 LTS databricks runtime.

Regards,
Saurabh

**Comment by Mahalakshmi1305** [comment]
Can you use runtime version 13.3LTS?
