### ISSUE TITLE
Unity catalog error Invalid configuration value detected for fs.azure.account.key

### ISSUE THREAD

**Issue by ecuellar2** [databrickslabs/overwatch#1183]
**Overwatch Version**
080 template: 080x_overwatch_deployment_config_template

**Describe the bug**
I am using 080 template. The storage_prefix is abfss://mycontainer@myadlsaccount.dfs.core.windows.net/foldername.
My external location in Azure Databricks is pointing to abfss://mycontainer@myadlsaccount.dfs.core.windows.net
I am using single user cluster and do not have passthrough enabled. I am the owner of the catalog and externa location.

.deploy() api is raising error below
KeyProviderException: Failure to initialize configuration for storage account  
Invalid configuration value detected for fs.azure.account.key
Caused by: InvalidConfigurationValueException

MultiWorkspaceDeployment.validate() completes without any issues. 
MultiWorkspaceDeployment(configCsvPath, tempLocation).deploy(1) is raising the error. 
I am deploying in one workspace, which is unity catalog enabled. 

Log4j output:
24/04/17 02:01:49 WARN FileSystem: Failed to initialize fileystem abfss://xx@xx.dfs.core.windows.net/foldername/global_share: Failure to initialize configuration for storage account xx.dfs.core.windows.net: Invalid configuration value detected for fs.azure.account.keyInvalid configuration value detected for fs.azure.account.key
24/04/17 02:01:49 ERROR MultiWorkspaceDeployment: FAILED DEPLOYMENT WITH EXCEPTION
Failure to initialize configuration for storage account xx.dfs.core.windows.net: Invalid configuration value detected for fs.azure.account.keyInvalid configuration value detected for fs.azure.account.key
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:52)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:670)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:2055)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:267)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:225)
	at com.databricks.common.filesystem.LokiFileSystem$.$anonfun$getLokiFS$1(LokiFileSystem.scala:64)
	at com.databricks.common.filesystem.Cache.getOrCompute(Cache.scala:38)
	at com.databricks.common.filesystem.LokiFileSystem$.getLokiFS(LokiFileSystem.scala:61)
	at com.databricks.common.filesystem.LokiFileSystem.initialize(LokiFileSystem.scala:87)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:537)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at com.databricks.unity.SAM.createDelegate(SAM.scala:149)
	at com.databricks.unity.SAM.createDelegate$(SAM.scala:142)
	at com.databricks.unity.ClusterDefaultSAM$.createDelegate(SAM.scala:159)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.createDelegate(CredentialScopeFileSystem.scala:83)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.$anonfun$setDelegates$1(CredentialScopeFileSystem.scala:136)
	at com.databricks.sql.acl.fs.Lazy.apply(DelegatingFileSystem.scala:310)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.getReadDelegate(CredentialScopeFileSystem.scala:96)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.getFileStatus(CredentialScopeFileSystem.scala:290)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
	at com.databricks.labs.overwatch.utils.Helpers$.pathExists(Tools.scala:186)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctionsUCE.dataTargetIsValid(InitializerFunctionsUCE.scala:54)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctionsUCE.validateAndSetDataTarget(InitializerFunctionsUCE.scala:88)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctions.validateAndRegisterArgs(InitializerFunctions.scala:91)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctions.validateAndRegisterArgs$(InitializerFunctions.scala:48)
	at com.databricks.labs.overwatch.pipeline.Initializer.validateAndRegisterArgs(Initializer.scala:14)
	at com.databricks.labs.overwatch.pipeline.Initializer$.apply(Initializer.scala:244)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:486)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: Invalid configuration value detected for fs.azure.account.key
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.diagnostics.ConfigurationBasicValidator.validate(ConfigurationBasicValidator.java:49)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.diagnostics.Base64StringConfigurationBasicValidator.validate(Base64StringConfigurationBasicValidator.java:40)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.validateStorageAccountKey(SimpleKeyProvider.java:71)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:49)
	... 38 more
24/04/17 02:01:49 ERROR ScalaDriverLocal: User Code Stack Trace: 
Failure to initialize configuration for storage account xxx.dfs.core.windows.net: Invalid configuration value detected for fs.azure.account.keyInvalid configuration value detected for fs.azure.account.key
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:52)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AbfsConfiguration.getStorageAccountKey(AbfsConfiguration.java:670)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.initializeClient(AzureBlobFileSystemStore.java:2055)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystemStore.<init>(AzureBlobFileSystemStore.java:267)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.AzureBlobFileSystem.initialize(AzureBlobFileSystem.java:225)
	at com.databricks.common.filesystem.LokiFileSystem$.$anonfun$getLokiFS$1(LokiFileSystem.scala:64)
	at com.databricks.common.filesystem.Cache.getOrCompute(Cache.scala:38)
	at com.databricks.common.filesystem.LokiFileSystem$.getLokiFS(LokiFileSystem.scala:61)
	at com.databricks.common.filesystem.LokiFileSystem.initialize(LokiFileSystem.scala:87)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3469)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:537)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
	at com.databricks.unity.SAM.createDelegate(SAM.scala:149)
	at com.databricks.unity.SAM.createDelegate$(SAM.scala:142)
	at com.databricks.unity.ClusterDefaultSAM$.createDelegate(SAM.scala:159)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.createDelegate(CredentialScopeFileSystem.scala:83)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.$anonfun$setDelegates$1(CredentialScopeFileSystem.scala:136)
	at com.databricks.sql.acl.fs.Lazy.apply(DelegatingFileSystem.scala:310)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.getReadDelegate(CredentialScopeFileSystem.scala:96)
	at com.databricks.sql.acl.fs.CredentialScopeFileSystem.getFileStatus(CredentialScopeFileSystem.scala:290)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
	at com.databricks.labs.overwatch.utils.Helpers$.pathExists(Tools.scala:186)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctionsUCE.dataTargetIsValid(InitializerFunctionsUCE.scala:54)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctionsUCE.validateAndSetDataTarget(InitializerFunctionsUCE.scala:88)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctions.validateAndRegisterArgs(InitializerFunctions.scala:91)
	at com.databricks.labs.overwatch.pipeline.InitializerFunctions.validateAndRegisterArgs$(InitializerFunctions.scala:48)
	at com.databricks.labs.overwatch.pipeline.Initializer.validateAndRegisterArgs(Initializer.scala:14)
	at com.databricks.labs.overwatch.pipeline.Initializer$.apply(Initializer.scala:244)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$executePipelines$1(MultiWorkspaceDeployment.scala:486)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: Invalid configuration value detected for fs.azure.account.key
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.diagnostics.ConfigurationBasicValidator.validate(ConfigurationBasicValidator.java:49)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.diagnostics.Base64StringConfigurationBasicValidator.validate(Base64StringConfigurationBasicValidator.java:40)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.validateStorageAccountKey(SimpleKeyProvider.java:71)
	at shaded.databricks.azurebfs.org.apache.hadoop.fs.azurebfs.services.SimpleKeyProvider.getStorageAccountKey(SimpleKeyProvider.java:49)
	... 38 more

**Comment by mohanbaabu1996** [comment]
Hi @ecuellar2 

Please make sure to add this [details](https://databrickslabs.github.io/overwatch/deployoverwatch/configureoverwatch/securityconsiderations/#azure-storage-auth-config) the Overwatch cluster - spark configurations

**Comment by ecuellar2** [comment]
Thank you. That resolved the error.
