### ISSUE TITLE
 NoSuchElementException: key not found: 2011  : Gold(workspace).run()

### ISSUE THREAD

**Issue by AbhimanyuSharmaMosaic** [databrickslabs/overwatch#119]
Hi, I am trying to setup Overwatch on Azure using the provided jars and environment configuration document, but consistently getting this error during gold pipeline run. Similar details in driver logs. Is this something known?

Bronze and Silver pipeline run were fine. 

Details: 
NoSuchElementException: key not found: 2011

at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at com.databricks.labs.overwatch.pipeline.Module.$anonfun$mostLaggingDependency$1(Module.scala:81)
	at com.databricks.labs.overwatch.pipeline.Module.$anonfun$mostLaggingDependency$1$adapted(Module.scala:81)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofInt.foreach(ArrayOps.scala:246)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofInt.map(ArrayOps.scala:246)
	at com.databricks.labs.overwatch.pipeline.Module.mostLaggingDependency(Module.scala:81)
	at com.databricks.labs.overwatch.pipeline.Module.untilTime(Module.scala:69)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:225)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1(Gold.scala:167)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1$adapted(Gold.scala:146)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:146)
	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:193)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:1)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:53)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:55)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:57)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:59)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:61)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw$$iw.<init>(command-2261199086756573:63)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw$$iw.<init>(command-2261199086756573:65)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw$$iw.<init>(command-2261199086756573:67)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$$iw.<init>(command-2261199086756573:69)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read.<init>(command-2261199086756573:71)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$.<init>(command-2261199086756573:75)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$read$.<clinit>(command-2261199086756573)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$eval$.$print$lzycompute(<notebook>:7)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$eval$.$print(<notebook>:6)
	at $lined4bf8c3935554fbda8ad2281d3c04f1b37.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:745)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1021)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:574)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:573)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:600)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:570)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:235)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:830)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:783)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:235)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$11(DriverLocal.scala:488)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:240)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:235)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:232)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:50)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:277)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:270)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:50)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:465)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:690)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:682)
	at com.databricks.backend.daemon.driver.DriverWrapper.getCommandOutputAndError(DriverWrapper.scala:523)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:635)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:428)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:371)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:223)
	at java.lang.Thread.run(Thread.java:748)

**Comment by alexott** [comment]
what version of Overwatch?

**Comment by GeekSheikh** [comment]
Thanks for reaching out.

This is telling you that you are missing the state (probably the entire table) for an upstream dependency. If you look in your ETL database, you should see a table, "jobrun_silver", if you do not, that is why you're receiving this error. If this table is missing, the error we need to look for is upstream. Ensure you have logging enabled on your Overwatch cluster and review the log4j logs for errors relating to Module 2011, "Silver_JobsRuns". You should also be able to find the related error in the "Pipeline Report" for module 2011. If you still cannot figure it out, please zip up all the logs and provide them and we'll take a look ASAP.

**Comment by GeekSheikh** [comment]
Hi, it does look like there was an error in some cases where there isn't much history in the audit logs. Sorry about that. Will be submitting patch for this today. Look for Overwatch version 0.4.11

**Comment by AbhimanyuSharmaMosaic** [comment]
@GeekSheikh Thanks for an update. 
To your previous comment, I reproduced the error and reviewed the created tables and log4j driver logs. You were right that table "Silver_JobRuns" didn't get create, but I did not receive any error running silver run pipeline. The error came only in gold run.
Also, during the review of log4j file for the error related to Module 2011, it was all INFO logs.

**Comment by AbhimanyuSharmaMosaic** [comment]
> what version of Overwatch?

I just noticed that I was using 0.4.0, as referred in the documentation for Maven, Overwatch Assembly (fat jar): com.databricks.labs:overwatch_2.12:0.4.0

But now will change databricks library to 0.4.11, once new changes are there.

**Comment by GeekSheikh** [comment]
> > what version of Overwatch?
> 
> I just noticed that I was using 0.4.0, as referred in the documentation for Maven, Overwatch Assembly (fat jar): com.databricks.labs:overwatch_2.12:0.4.0
> 
> But now will change databricks library to 0.4.11, once new changes are there.

Great, glad it's working. 

Note that the reason you think you didn't get an error while it was running silver is because these are soft errors meaning a single module fail will not kill the pipeline, it will continue on and log the error. Additionally, downstream dependencies will also not get data until that error is resolved. This is by design, so when you see some error, go to pipeline_report and review the dependencies. The module dependency map can be found [here](https://databrickslabs.github.io/overwatch/dataengineer/etl_process/#module-dependencies).
