### ISSUE TITLE
[AMBIGUOUS_REFERENCE] Reference `accountId` is ambiguous, could be: [`accountId`, `accountId`]

### ISSUE THREAD

**Issue by arodriguezf** [databrickslabs/overwatch#1310]
Hello team!
I´m updating overwatch from version 0.7.2.2.1 to version 0.8.0.0 (and I will continue updating to the last version). The update was fine (executing the notebook to update config), but after that, running the overwatch pipeline, I got a problem during the process:
```
Beginning: 2010-Silver_JobsStatus --> Workspace ID: 6720070993575571
TIME RANGE: 2024-11-19 16:10:27 -> 2024-12-02 07:40:46

Beginning: 2008-Silver_SPARK_Tasks --> Workspace ID: 5769108933149883
TIME RANGE: 2024-11-29 09:50:41 -> 2024-12-02 07:40:49

Silver_JobsStatus: Validating Input Schemas
Silver_SPARK_Tasks: Validating Input Schemas
FAILED: 2010-Silver_JobsStatus Module: Failed

[AMBIGUOUS_REFERENCE] Reference `accountId` is ambiguous, could be: [`accountId`, `accountId`]. SQLSTATE: 42704
org.apache.spark.sql.AnalysisException: [AMBIGUOUS_REFERENCE] Reference `accountId` is ambiguous, could be: [`accountId`, `accountId`]. SQLSTATE: 42704
	at org.apache.spark.sql.errors.QueryCompilationErrors$.ambiguousReferenceError(QueryCompilationErrors.scala:2525)
	at org.apache.spark.sql.catalyst.expressions.package$AttributeSeq.resolve(package.scala:407)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveChildren(LogicalPlan.scala:183)
```
Do you know if there is some bug on the version or what can I do with that? Since I can´t modify the queries to put some aliases on them, I don´t know what to do there.
Thanks!

**Comment by arodriguezf** [comment]
Btw, I´m using DBR: 15.4 LTS (includes Apache Spark 3.5.0, Scala 2.12)
