### ISSUE TITLE
No FileSystem for scheme: abfss

### ISSUE THREAD

**Issue by gxtaillon** [databrickslabs/overwatch#133]
Hi,

I`m trying to setup overwatch on ADLS Gen2 from my workspace and the setup fails in the Initializer with the following error:

```
IOException: No FileSystem for scheme: abfss
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
	at com.databricks.labs.overwatch.utils.Helpers$.pathExists(Tools.scala:572)
	at com.databricks.labs.overwatch.pipeline.Initializer.dataTargetIsValid(Initializer.scala:265)
	at com.databricks.labs.overwatch.pipeline.Initializer.com$databricks$labs$overwatch$pipeline$Initializer$$validateAndRegisterArgs(Initializer.scala:198)
	at com.databricks.labs.overwatch.pipeline.Initializer$.apply(Initializer.scala:434)
```

spark.read.* & dbutils in Scala works from the same workspace/cluster with the same ADLS.

This forced me to create a mount point to workaround this.

**Comment by alexott** [comment]
Fix will be available soon

**Comment by GeekSheikh** [comment]
staged for prod release in 0.4.2 version. 0.4.2 is in final integration testing, will be released soon.
