### ISSUE TITLE
Silver_JobsStatus: Failed - Number of partitions (0) must be positive.

### ISSUE THREAD

**Issue by cmcharg-dufrain** [databrickslabs/overwatch#590]
Hi,

I recently deployed new version of overwatch 0.7.0.0.1 and getting following failure on Silver_JobStatus:

FAILED --> 
ERROR:
Silver_JobsStatus FAILED -->

requirement failed: Number of partitions (0) must be positive.
java.lang.IllegalArgumentException: requirement failed: Number of partitions (0) must be positive.
	at scala.Predef$.require(Predef.scala:281)
	at org.apache.spark.sql.catalyst.plans.logical.Repartition.<init>(basicLogicalOperators.scala:1683)
	at org.apache.spark.sql.Dataset.repartition(Dataset.scala:3220)
	at com.databricks.labs.overwatch.pipeline.WorkflowsTransforms$.jobStatusStructifyJsonCols(WorkflowsTransforms.scala:428)
	at com.databricks.labs.overwatch.pipeline.SilverTransforms.$anonfun$dbJobsStatusSummary$3(SilverTransforms.scala:1137)
	at org.apache.spark.sql.Dataset.transform(Dataset.scala:2906)
	at com.databricks.labs.overwatch.pipeline.SilverTransforms.dbJobsStatusSummary(SilverTransforms.scala:1137)
	at com.databricks.labs.overwatch.pipeline.SilverTransforms.dbJobsStatusSummary$(SilverTransforms.scala:1090)
	at com.databricks.labs.overwatch.pipeline.Silver.dbJobsStatusSummary(Silver.scala:7)
	at com.databricks.labs.overwatch.pipeline.Silver.$anonfun$appendJobStatusProcess$1(Silver.scala:235)
	at org.apache.spark.sql.Dataset.transform(Dataset.scala:2906)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.$anonfun$executeETL$1(ETLDefinition.scala:30)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.executeETL(ETLDefinition.scala:28)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:352)
	at com.databricks.labs.overwatch.pipeline.Silver.$anonfun$executeModules$1(Silver.scala:350)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Silver.executeModules(Silver.scala:334)
	at com.databricks.labs.overwatch.pipeline.Silver.run(Silver.scala:360)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:1)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:63)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:65)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:67)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:69)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:71)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:73)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:75)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:77)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-706264495640116:79)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw$$iw.<init>(command-706264495640116:81)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw$$iw.<init>(command-706264495640116:83)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw$$iw.<init>(command-706264495640116:85)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$$iw.<init>(command-706264495640116:87)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read.<init>(command-706264495640116:89)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$.<init>(command-706264495640116:93)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$read$.<clinit>(command-706264495640116)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$eval$.$print$lzycompute(<notebook>:7)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$eval$.$print(<notebook>:6)
	at $line633ebc7f7aaa48ee9d83dcd89d589e3449.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:225)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:999)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:952)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$12(DriverLocal.scala:631)
	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:59)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:59)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:608)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:615)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:607)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:526)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:561)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:431)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
	at java.lang.Thread.run(Thread.java:748)

Could you advise on how to resolve this error?

Thanks

**Comment by Neha-vs123** [comment]
Hi @cmcharg-dufrain ,

What cluster library you have used? Is it 0700 or 07001? 

Regards,
Neha

**Comment by cmcharg-dufrain** [comment]
Cluster Setup is as follows:

Main class: com.databricks.labs.overwatch.BatchRunner
Dependent Libraries:
com.databricks.labs:overwatch_2.12:0.7.0.0.1
com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.21

**Comment by Neha-vs123** [comment]
@cmcharg-dufrain , Could you please send the pipeline report from the ETL database? 

select * from <etl database name>.pipeline_report

Is this the first run of Overwatch or were there any successful runs before ?

**Comment by cmcharg-dufrain** [comment]
Attached is pipeline report. We have run overwatch daily for the last few days however none of these runs have sucessfully run Silver_JobStatus.

[pipeline_report.csv](https://github.com/databrickslabs/overwatch/files/9888017/pipeline_report.csv)

**Comment by Neha-vs123** [comment]
@cmcharg-dufrain Are you using single node cluster ?
Overwatch is too big for single node cluster anyway, please change cluster to multi node and re-run the process.
Kindly send me the pipeline_report after re-running the job

**Comment by GeekSheikh** [comment]
Overwatch will work on some workspaces on a single-node cluster but if there is much data we do recommend a traditional cluster. That said, there was a bug with single-node clusters for 7.0.x which is fixed in 0.7.0.0.2 coming out later this week.

**Comment by Neha-vs123** [comment]
@cmcharg-dufrain, Are you still facing the issue?

**Comment by GeekSheikh** [comment]
Hello, Issue #577 was closed and merged into 07002. You should be able to execute on single-node clusters now even though this may fail for other reasons if the workload is too large for a single node and/or the type of node selected.

Closing this for now as I believe this is resolved, please feel free to re-open if your issue is not resolved.
