### ISSUE TITLE
Changing Event Hub

### ISSUE THREAD

**Issue by cmcharg-dufrain** [databrickslabs/overwatch#630]
Hi,

Is it possible to change the event hub which overwatch reads diagnostic logs from?

I have updated the job parameters but I am getting the following error when running the new job:

StreamingQueryException: Query StreamTo_audit_log_raw_events [id = f2ee7150-5c03-49dd-bb2e-9a4a5af97923, runId = dbe0642f-72a9-45b0-8e83-c04d4473c87f] terminated with exception: key not found: {"ehName":"evh-dtalake-dataplatform-devtest-ne01","partitionId":1}
Caused by: NoSuchElementException: key not found: {"ehName":"evh-dtalake-dataplatform-devtest-ne01","partitionId":1}

The ehName: evh-dtalake-dataplatform-devtest-ne01 is the previous event hub used.

Thanks

**Comment by AnushaSure** [comment]
Hi @cmcharg-dufrain,

Please run the attached readiness review notebook with the new event hub details and see the EH section. If you found any issue, please share the html file of that notebook.

Regards,
Anusha
[ReadinessReview - Latest.zip](https://github.com/databrickslabs/overwatch/files/10072393/ReadinessReview.-.Latest.zip)

**Comment by AnushaSure** [comment]
Hi @cmcharg-dufrain, 

Yes, it is possible to change event hub but make sure that you have consumed all the data from the old EH.

Regards,
Anusha

**Comment by cmcharg-dufrain** [comment]
Hi @AnushaSure I was able to successfully run the notebook you mentioned however I am still receiving the same error when trying to run the overwatch job.

**Comment by AnushaSure** [comment]
Please share the html file of readiness review notebook run.

Regards,
Anusha

**Comment by cmcharg-dufrain** [comment]
Hi Anusha,

I dont think I can share the file as it contains connections strings/keys etc. The final command "display(rawEHDF)" of the notebook runs successfully however and streams data from event hubs.

The full error when running the job itself with new event hub is below:

StreamingQueryException: Query StreamTo_audit_log_raw_events [id = f2ee7150-5c03-49dd-bb2e-9a4a5af97923, runId = c1fb9406-5b0f-4cea-aea3-41e647ff2d15] terminated with exception: key not found: {"ehName":"evh-dtalake-dataplatform-devtest-ne01","partitionId":1}
Caused by: NoSuchElementException: key not found: {"ehName":"evh-dtalake-dataplatform-devtest-ne01","partitionId":1}
=== Streaming Query ===
Identifier: StreamTo_audit_log_raw_events [id = f2ee7150-5c03-49dd-bb2e-9a4a5af97923, runId = c1fb9406-5b0f-4cea-aea3-41e647ff2d15]
Current Committed Offsets: {org.apache.spark.sql.eventhubs.EventHubsSource@3f89bed3: {"evh-dtalake-dataplatform-devtest-ne01":{"1":2232,"0":2227}}}
Current Available Offsets: {org.apache.spark.sql.eventhubs.EventHubsSource@3f89bed3: {"evh-dtalake-dataplatform-devtest-ne01":{"1":2283,"0":2280}}}

Current State: ACTIVE
Thread State: RUNNABLE

Logical Plan:
WriteToMicroBatchDataSourceV1 DeltaSink[/mnt/clusterlogs/global_share/audit_log_raw_events], f2ee7150-5c03-49dd-bb2e-9a4a5af97923, [queryName=StreamTo_audit_log_raw_events, path=/mnt/clusterlogs/global_share/audit_log_raw_events, checkpointLocation=/mnt/clusterlogs/3179183024797946/ehState/rawEventsCheckpoint, mergeSchema=true, userMetadata=*********(redacted)], Append
+- Project [body#398531, partition#398532, offset#398533, sequenceNumber#398534L, enqueuedTime#398535, publisher#398536, partitionKey#398537, properties#398538, systemProperties#398539, deserializedBody#398549, organization_id#398560, Overwatch_RunID#398572, Pipeline_SnapTS#398585, 3179183024797946 AS workspace_name#398599]
   +- Project [body#398531, partition#398532, offset#398533, sequenceNumber#398534L, enqueuedTime#398535, publisher#398536, partitionKey#398537, properties#398538, systemProperties#398539, deserializedBody#398549, organization_id#398560, Overwatch_RunID#398572, cast(from_unixtime(cast((cast(1669196908336 as double) / cast(1000 as double)) as bigint), yyyy-MM-dd HH:mm:ss, Some(Etc/UTC)) as timestamp) AS Pipeline_SnapTS#398585]
      +- Project [body#398531, partition#398532, offset#398533, sequenceNumber#398534L, enqueuedTime#398535, publisher#398536, partitionKey#398537, properties#398538, systemProperties#398539, deserializedBody#398549, organization_id#398560, 554c2b61911f43bb87694391d95f48d8 AS Overwatch_RunID#398572]
         +- Project [body#398531, partition#398532, offset#398533, sequenceNumber#398534L, enqueuedTime#398535, publisher#398536, partitionKey#398537, properties#398538, systemProperties#398539, deserializedBody#398549, 3179183024797946 AS organization_id#398560]
            +- Project [body#398531, partition#398532, offset#398533, sequenceNumber#398534L, enqueuedTime#398535, publisher#398536, partitionKey#398537, properties#398538, systemProperties#398539, cast(body#398531 as string) AS deserializedBody#398549]
               +- StreamingExecutionRelation org.apache.spark.sql.eventhubs.EventHubsSource@3f89bed3, [body#398531, partition#398532, offset#398533, sequenceNumber#398534L, enqueuedTime#398535, publisher#398536, partitionKey#398537, properties#398538, systemProperties#398539]

	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:403)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.$anonfun$run$4(StreamExecution.scala:269)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:104)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:269)
Caused by: java.util.NoSuchElementException: key not found: {"ehName":"evh-dtalake-dataplatform-devtest-ne01","partitionId":1}
	at scala.collection.MapLike.default(MapLike.scala:236)
	at scala.collection.MapLike.default$(MapLike.scala:235)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:65)
	at org.apache.spark.sql.eventhubs.EventHubsSource.$anonfun$adjustStartingOffset$1(EventHubsSource.scala:250)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.immutable.Map$Map2.foreach(Map.scala:273)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.apache.spark.sql.eventhubs.EventHubsSource.adjustStartingOffset(EventHubsSource.scala:248)
	at org.apache.spark.sql.eventhubs.EventHubsSource.getBatch(EventHubsSource.scala:367)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$populateStartOffsets$3(MicroBatchExecution.scala:475)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at org.apache.spark.sql.execution.streaming.StreamProgress.foreach(StreamProgress.scala:27)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.populateStartOffsets(MicroBatchExecution.scala:472)
	at org.apache.spark.sql.execution.streaming.MultiBatchRollbackSupport.populateStartOffsetsWithRollbackHandling(MultiBatchRollbackSupport.scala:112)
	at org.apache.spark.sql.execution.streaming.MultiBatchRollbackSupport.populateStartOffsetsWithRollbackHandling$(MultiBatchRollbackSupport.scala:79)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.populateStartOffsetsWithRollbackHandling(MicroBatchExecution.scala:55)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStreamWithListener$2(MicroBatchExecution.scala:337)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:320)
	at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:318)
	at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:77)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStreamWithListener$1(MicroBatchExecution.scala:327)
	at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:67)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStreamWithListener(MicroBatchExecution.scala:317)
	at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:305)
	at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:380)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:344)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.$anonfun$run$4(StreamExecution.scala:269)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.unity.EmptyHandle$.runWithAndClose(UCSHandle.scala:104)
	at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:269)

**Comment by AnushaSure** [comment]
Apart from clearing the ehState, I would rather suggest to rename the ehState and move to another location for future reference.

Is the old event hub deleted ?, please confirm

Regards,
Anusha

**Comment by cmcharg-dufrain** [comment]
So to confirm I can rename ehState and move to another location?

The old event hub still exists.

**Comment by AnushaSure** [comment]
Yes, you can rename and move.

If possible we can schedule a call and discuss.
Mail_id - anusha.sure@databricks.com

Regards,
Anusha
