### ISSUE TITLE
Tables not updating because FROM and UNTIL times are identical and jobruncostpotentialfact cannot be created

### ISSUE THREAD

**Issue by YitianLiu9** [databrickslabs/overwatch#725]
Hi, 

We updated from version 0.7.0.0.4 to 0.7.1 and a few modules are not reading new data. The pipeline report and the logs shows that the FROM and UNTIL times are identical. Could you please advise? Thank you! 

This is what is shown in status: EMPTY: EMPTY: 3001-Gold_Cluster Module: SKIPPING
Downstream modules that depend on this module will not progress until new data is received by this module.
 Module Dependencies: 2014, 2019
FROM and UNTIL times are identical. Likely due to upstream dependencies being at or ahead of current module.
com.databricks.labs.overwatch.utils.NoNewDataException: FROM and UNTIL times are identical. Likely due to upstream dependencies being at or ahead of current module.
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:345)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1(Gold.scala:279)
	at com.databricks.labs.overwatch.pipeline.Gold.$anonfun$executeModules$1$adapted(Gold.scala:262)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Gold.executeModules(Gold.scala:262)
	at com.databricks.labs.overwatch.pipeline.Gold.run(Gold.scala:355)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startGoldDeployment(MultiWorkspaceDeployment.scala:228)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$deploy$4(MultiWorkspaceDeployment.scala:379)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
	
A screenshot of the logging in the notebook
<img width="824" alt="Screen Shot 2023-02-08 at 1 46 42 PM" src="https://user-images.githubusercontent.com/120654490/217533591-647079ac-fd29-41e7-b301-34dbd7b20e31.png">

**Comment by YitianLiu9** [comment]
Also, the jobruncostpotentialfact table was not created. Could you please advise here as well. Thank you! 

Here is the error from the log in the notebook. 

<img width="841" alt="Screen Shot 2023-02-08 at 2 12 29 PM" src="https://user-images.githubusercontent.com/120654490/217539717-d5bbdbfb-4384-4e31-82ec-415f58211eb6.png">

**Comment by mohanbaabu1996** [comment]
Hi @YitianLiu9 ,

Have you run this [script ](https://databrickslabs.github.io/overwatch/changelog/#07005-patch)before upgrading to 0710 ?

**Comment by YitianLiu9** [comment]
Hi @mohanbaabu1996 , 

Thanks for your reply. I didn't run this script. Can I run it now or do I have to fix something first? Cause I already run the 0710 version.

**Comment by YitianLiu9** [comment]
Hi @mohanbaabu1996 , 

Could I possibly get an email address from you or schedule a meeting together? The data cannot be shared here for various reasons. And we are using Azure. Thank you!!

**Comment by GeekSheikh** [comment]
You should be able to just run the script. It will repair the data. Sorry for the inconvenience, if you run into any issues we'll get a meeting to help you out.

**Comment by YitianLiu9** [comment]
Hi @GeekSheikh , It says "AnalysisException: Table or view not found: overwatch_etl.cluster_events_bronze;", could you please advise? Thank you!

**Comment by mohanbaabu1996** [comment]
Hi @YitianLiu9 ,

can you make sure your ETL database name is "overwatch_etl" ?

![Uploading image.png…]()

**Comment by YitianLiu9** [comment]
Yes it is. The only cluster related tables I can find in overwatch_etl are cluster_spec_silver and clusters_snapshot_bronze. Perhaps you changed the name of the table in 0710?

**Comment by mohanbaabu1996** [comment]
No, table name is correct.
Need to understand what happened to that module.
I need those reports which i mentioned earlier to understand why that table is not populated.

**Comment by YitianLiu9** [comment]
Okay. Can I send it to you via email? Thanks

**Comment by mohanbaabu1996** [comment]
Sure, mohan.baabu@databricks.com is my ID

**Comment by mohanbaabu1996** [comment]
Hi @YitianLiu9 ,

Thanks for the report, i could see your Bronze_ClusterEventLogs  is failing

```FAILED --> 
ERROR:
Bronze_ClusterEventLogs FAILED -->

Failed to merge fields 'details' and 'details'. Failed to merge fields 'attributes' and 'attributes'. Failed to merge fields 'azure_attributes' and 'azure_attributes'. Failed to merge incompatible data types StructType(StructField(availability,StringType,true),StructField(first_on_demand,LongType,true),StructField(spot_bid_max_price,DoubleType,true)) and MapType(StringType,StringType,true)
org.apache.spark.sql.AnalysisException: Failed to merge fields 'details' and 'details'. Failed to merge fields 'attributes' and 'attributes'. Failed to merge fields 'azure_attributes' and 'azure_attributes'. Failed to merge incompatible data types StructType(StructField(availability,StringType,true),StructField(first_on_demand,LongType,true),StructField(spot_bid_max_price,DoubleType,true)) and MapType(StringType,StringType,true)
	at com.databricks.sql.transaction.tahoe.schema.SchemaMergingUtils$.$anonfun$mergeSchemas$1(SchemaMergingUtils.scala:204)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at com.databricks.sql.transaction.tahoe.schema.SchemaMergingUtils$.merge$1(SchemaMergingUtils.scala:184)
	at com.databricks.sql.transaction.tahoe.schema.SchemaMergingUtils$.mergeSchemas(SchemaMergingUtils.scala:283)
	at com.databricks.sql.transaction.tahoe.schema.ImplicitMetadataOperation$.mergeSchema(ImplicitMetadataOperation.scala:161)
	at com.databricks.sql.transaction.tahoe.schema.ImplicitMetadataOperation.updateMetadata(ImplicitMetadataOperation.scala:67)
	at com.databricks.sql.transaction.tahoe.schema.ImplicitMetadataOperation.updateMetadata$(ImplicitMetadataOperation.scala:55)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.updateMetadata(WriteIntoDelta.scala:78)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.write(WriteIntoDelta.scala:235)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$2(WriteIntoDelta.scala:110)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$2$adapted(WriteIntoDelta.scala:99)
	at com.databricks.sql.transaction.tahoe.DeltaLog.withNewTransaction(DeltaLog.scala:306)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:99)
	at com.databricks.sql.acl.CheckPermissions$.trusted(CheckPermissions.scala:1776)
	at com.databricks.sql.transaction.tahoe.commands.WriteIntoDelta.run(WriteIntoDelta.scala:98)
	at com.databricks.sql.transaction.tahoe.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:168)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:49)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:78)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:89)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$2(QueryExecution.scala:246)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:243)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:392)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:188)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:985)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:142)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:342)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:246)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$withMVTagsIfNecessary(QueryExecution.scala:231)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:244)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:237)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:99)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:512)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:268)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:488)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:237)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:237)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:191)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:182)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:273)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:965)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:430)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:339)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:251)
	at com.databricks.labs.overwatch.env.Database.write(Database.scala:246)
	at com.databricks.labs.overwatch.env.Database.executeRetry$1(Database.scala:267)
	at com.databricks.labs.overwatch.env.Database.performRetry(Database.scala:282)
	at com.databricks.labs.overwatch.env.Database.writeWithRetry(Database.scala:302)
	at com.databricks.labs.overwatch.pipeline.Pipeline.append(Pipeline.scala:430)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$appendClusterEventLogsProcess$2(Bronze.scala:145)
	at com.databricks.labs.overwatch.pipeline.ETLDefinition.executeETL(ETLDefinition.scala:32)
	at com.databricks.labs.overwatch.pipeline.Module.execute(Module.scala:352)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1(Bronze.scala:212)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Bronze.executeModules(Bronze.scala:205)
	at com.databricks.labs.overwatch.pipeline.Bronze.run(Bronze.scala:232)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.startBronzeDeployment(MultiWorkspaceDeployment.scala:180)
	at com.databricks.labs.overwatch.MultiWorkspaceDeployment.$anonfun$deploy$4(MultiWorkspaceDeployment.scala:375)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```
@GeekSheikh They couldn't select this table and not able to run the repair script.

"AnalysisException: Table or view not found: overwatch_etl.cluster_events_bronze;

**Comment by GeekSheikh** [comment]
@mohanbaabu1996 -- this is still because of 07004 issue. Make sure you check the data dir, if there is data present there and no table, drop the data dir, do a full rollback for that module and downstream modules and rerun. Note that any history >30d will be lost via this method. If historical data >30d needs to be maintained, and the data is present in the data dir, we need to use a different process.

**Comment by mohanbaabu1996** [comment]
@GeekSheikh They've did a clean and ran as a fresh start. 

`The clean up and restart have succeeded. Thank you for your help. But the cost issue still persists, that the dbu cost provided by Overwatch is less than the dbu cost from Azure Reservation. Both are calculated with standard rate, not considering the discount. Could you please help here? `

**Comment by mohanbaabu1996** [comment]
@YitianLiu9 Hope you doing good!
Thanks for your patience.
Overwatch's upcoming [update](https://databrickslabs.github.io/overwatch/changelog/), which enhances the costing aspect, will launch either today or early next week. Once the release done, please do the clean up steps which i mentioned in the email and re-run the overwatch job. Ping me over mail if you've any issues.
Thanks!
