### ISSUE TITLE
[BUG] - AWS Single Tenant - MultiWorkspace Deployment - None.get

### ISSUE THREAD

**Issue by GeekSheikh** [databrickslabs/overwatch#788]
the updated Initializer.getOrgId is returning a null dbuitls.notebook.getContext.apiUrl.get when executed as a multi-workspace deployment 

ONLY WHEN

Run as a JAR - main class
On automated cluster

**Comment by GeekSheikh** [comment]
full stack trace -- the `MultiWorkspaceDeployment(...).deploy(...)` is confirmed working so it's just the `.validate` function that is getting the issue. 

```
NoSuchElementException: None.get
	at scala.None$.get(Option.scala:529)
	at scala.None$.get(Option.scala:527)
	at com.databricks.labs.overwatch.pipeline.Initializer$.getOrgId(Initializer.scala:567)
	at com.databricks.labs.overwatch.validation.DeploymentValidation$.validateMountCount(DeploymentValidation.scala:174)
	at com.databricks.labs.overwatch.validation.DeploymentValidation$.$anonfun$performValidation$5(DeploymentValidation.scala:703)
	at scala.collection.parallel.mutable.ParArray$Map.leaf(ParArray.scala:659)
	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
	at scala.collection.parallel.mutable.ParArray$Map.tryLeaf(ParArray.scala:650)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```
